In [1]:
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()

In [10]:
timeseries.head(50)

                         id  time  F_x  F_y  F_z  T_x  T_y  T_z
_temporary_index_column
0                         1     0   -1   -1   63   -3   -1    0
1                         1     1    0    0   62   -3   -1    0
2                         1     2   -1   -1   61   -3    0    0
3                         1     3   -1   -1   63   -2   -1    0
4                         1     4   -1   -1   63   -3   -1    0
5                         1     5   -1   -1   63   -3   -1    0
6                         1     6   -1   -1   63   -3    0    0
7                         1     7   -1   -1   63   -3   -1    0
8                         1     8   -1   -1   63   -3   -1    0
9                         1     9   -1   -1   61   -3    0    0
10                        1    10   -1   -1   61   -3    0    0
11                        1    11   -1   -1   64   -3   -1    0
12                        1    12   -1   -1   64   -3   -1    0
13                        1    13   -1   -1   60   -3    0    0
14                        1    14   -1    0   64   -2   -1    0
15                        2     0   -1   -1   63   -2   -1    0
16                        2     1   -1   -1   63   -3   -1    0
17                        2     2   -1   -1   61   -3    0    0
18                        2     3    0   -4   63    1    0    0
19                        2     4    0   -1   59   -2    0   -1
20                        2     5   -3    3   57   -8   -3   -1
21                        2     6   -1    3   70  -10   -2   -1
22                        2     7    0   -3   61    0    0    0
23                        2     8    0   -2   53   -1   -2    0
24                        2     9    0   -3   66    1    4    0
25                        2    10   -3    3   58  -10   -5    0
26                        2    11   -1   -1   66   -4   -2    0
27                        2    12   -1   -2   67   -3   -1    0
28                        2    13    0    1   66   -6   -3   -1
29                        2    14   -1   -1   59   -3   -4    0
30                        3     0   -1    0   57   -5   -3    0
31                        3     1    0   -3   63   -1    0    0
32                        3     2   -1    1   51   -4   -1   -1
33                        3     3   -1   -2   68   -2   -2    0
34                        3     4   -1   -1   65   -6    1    0
35                        3     5    0    0   61   -5   -2    0
36                        3     6   -1    1   61   -6    0   -1
37                        3     7    0   -3   57    3   -4    0
38                        3     8   -1   -1   59   -4   -4    0
39                        3     9    1   -3   65   -1    1    0
40                        3    10   -1    2   64   -7   -2    0
41                        3    11   -1    1   66   -7   -3   -1
42                        3    12   -1    0   61   -5   -5    0
43                        3    13   -1    0   65   -6   -2   -1
44                        3    14   -1    0   54   -4   -3    0
45                        4     0    0   -1   59   -2   -1   -1
46                        4     1    0   -3   61   -1    2    0
47                        4     2   -2    1   56   -6   -3    0
48                        4     3    1   -3   64   -1    4    0
49                        4     4   -1    1   62   -7    1   -1

In [9]:
y.head(20)

1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19    False
20    False
dtype: bool

In [3]:
timeseries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1320 non-null   int64
 1   time    1320 non-null   int64
 2   F_x     1320 non-null   int64
 3   F_y     1320 non-null   int64
 4   F_z     1320 non-null   int64
 5   T_x     1320 non-null   int64
 6   T_y     1320 non-null   int64
 7   T_z     1320 non-null   int64
dtypes: int64(8)
memory usage: 82.6 KB

In [4]:
import matplotlib.pyplot as plt
timeseries[timeseries['id'] == 3].plot(subplots=True, sharex=True, figsize=(10,10))
plt.show()

In [5]:
from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")

Feature Extraction: 100%|██████████████████████████████████████████████████████████████| 10/10 [00:35<00:00,  3.57s/it]

In [6]:
extracted_features

variable,F_x__abs_energy,F_x__absolute_sum_of_changes,"F_x__agg_autocorrelation__f_agg_""mean""__maxlag_40","F_x__agg_autocorrelation__f_agg_""median""__maxlag_40","F_x__agg_autocorrelation__f_agg_""var""__maxlag_40","F_x__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","F_x__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","F_x__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","F_x__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""","F_x__agg_linear_trend__attr_""intercept""__chunk_len_50__f_agg_""max""",...,T_z__symmetry_looking__r_0.9500000000000001,T_z__time_reversal_asymmetry_statistic__lag_1,T_z__time_reversal_asymmetry_statistic__lag_2,T_z__time_reversal_asymmetry_statistic__lag_3,T_z__value_count__value_-1,T_z__value_count__value_0,T_z__value_count__value_1,T_z__variance,T_z__variance_larger_than_standard_deviation,T_z__variation_coefficient
id,,,,,,,,,,,,,,,,,,,,,
1,14.0,2.0,-0.106351,-7.206633e-02,0.016879,0.0,-0.9,-1.0,0.09,NaN,...,0.0,0.000000,0.000000,0.000000,0.0,15.0,0.0,0.000000,0.0,NaN
2,25.0,14.0,-0.039098,-4.935275e-02,0.088790,0.0,-0.7,-3.0,0.81,NaN,...,1.0,0.000000,0.000000,0.000000,4.0,11.0,0.0,0.195556,0.0,-1.658312
3,12.0,10.0,-0.029815,1.301043e-17,0.105435,1.0,-0.5,-1.0,0.45,NaN,...,1.0,0.000000,-0.090909,0.000000,4.0,11.0,0.0,0.195556,0.0,-1.658312
4,16.0,17.0,-0.049773,-6.417112e-02,0.143580,1.0,-0.4,-2.0,1.24,NaN,...,1.0,0.000000,-0.181818,0.000000,6.0,8.0,1.0,0.355556,0.0,-1.788854
5,17.0,13.0,-0.061467,-5.172414e-02,0.052642,2.0,-0.5,-2.0,1.05,NaN,...,1.0,-0.076923,-0.090909,-0.222222,4.0,9.0,2.0,0.382222,0.0,-4.636809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,96833.0,100.0,-0.435813,-8.343714e-01,0.538354,-25.0,-55.3,-110.0,1216.61,NaN,...,1.0,-1254.846154,-3182.363636,-6043.333333,1.0,1.0,0.0,93.315556,1.0,-0.624569
85,1683.0,19.0,-0.599870,-4.380362e-01,0.991429,12.0,6.7,4.0,5.01,NaN,...,1.0,-34.846154,-57.545455,-84.000000,1.0,1.0,0.0,4.648889,1.0,-0.621960
86,83497.0,127.0,-0.603352,-4.802260e-01,0.994691,70.0,40.4,21.0,236.84,NaN,...,1.0,81.538462,141.000000,280.888889,0.0,0.0,1.0,29.840000,1.0,-1.011593
87,1405437.0,181.0,-0.455727,-4.355676e-01,0.516457,340.0,281.0,171.0,3848.20,NaN,...,1.0,8445.769231,16935.636364,25770.555556,0.0,0.0,0.0,98.088889,1.0,0.312757
88,1427.0,11.0,-0.614351,-5.887814e-01,1.121329,-6.0,-8.4,-11.0,1.84,NaN,...,1.0,14.230769,27.181818,36.222222,0.0,0.0,0.0,0.782222,0.0,0.181733

In [ ]:
import seaborn as sns
plt.figure(figsize = (12, 6))
sns.heatmap(extracted_features.corr(), cmap = 'coolwarm', annot = True)