## Imports and Data preparation

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import scale
from keras.models import Sequential
from keras.layers import Dense, Dropout
import matplotlib.pyplot as plt
import seaborn as sns

from keras.models import Sequential
from keras.layers import Dense


from tsfresh import extract_features, select_features, extract_relevant_features

#pd.set_option('display.max_columns', None)  # or 1000
#pd.set_option('display.max_rows', None) 

sdata = pd.read_csv(r"D:\BSC IT DOCX\Research Papers\Research Internship-Columbia\Indoor localization\DatasetV2\magneticcenterHall02.csv")
sdata1 = pd.read_csv(r"D:\BSC IT DOCX\Research Papers\Research Internship-Columbia\Indoor localization\DatasetV2\\magneticcenterKitchen02.csv")
sdata2 = pd.read_csv(r"D:\BSC IT DOCX\Research Papers\Research Internship-Columbia\Indoor localization\DatasetV2\\magneticcenterRoom03.csv")

sdata.columns = ['TimeStamp', 'X', 'Y', 'Z', 'Magnitude', 'CoordinateID']
sdata1.columns = ['TimeStamp', 'X', 'Y', 'Z', 'Magnitude', 'CoordinateID']
sdata2.columns = ['TimeStamp', 'X', 'Y', 'Z', 'Magnitude', 'CoordinateID']

Using TensorFlow backend.

In [2]:
# Check the shape of the data

print(sdata.shape,
sdata1.shape,
sdata2.shape)


#Exploratory Data Analysis

df = pd.concat([sdata, sdata1, sdata2], axis=0)

df = df.reset_index(drop=True)

df.head(10000)

(1914, 6) (1669, 6) (1385, 6)

,TimeStamp,X,Y,Z,Magnitude,CoordinateID
0,2020-08-17 05:25:08:174,51.780000,-91.020000,30.599998,58.613036,1
1,2020-08-17 05:25:08:194,52.020000,-91.619995,30.539999,58.783775,1
2,2020-08-17 05:25:08:214,52.199997,-92.100000,30.119999,58.718430,1
3,2020-08-17 05:25:08:234,52.800000,-92.159996,30.119999,59.251448,1
4,2020-08-17 05:25:08:254,52.739998,-92.220000,30.420000,59.350180,1
...,...,...,...,...,...,...
4963,2020-08-17 05:28:53:429,22.439999,-33.420000,-13.740000,25.010020,3
4964,2020-08-17 05:28:53:449,21.960000,-33.540000,-13.500000,24.442004,3
4965,2020-08-17 05:28:53:469,22.080000,-33.600000,-13.740000,24.680235,3
4966,2020-08-17 05:28:53:489,21.960000,-33.300000,-13.200000,24.287477,3
4967,2020-08-17 05:28:53:509,21.779999,-33.420000,-13.500000,24.285352,3

### Making sure that the data is in proper format for tsfresh feature extraction.

In [3]:
df = df.drop(['X'], axis = 1) 
df = df.drop(['Y'], axis = 1) 
df = df.drop(['Z'], axis = 1) 
df

                    TimeStamp  Magnitude  CoordinateID
0     2020-08-17 05:25:08:174  58.613036             1
1     2020-08-17 05:25:08:194  58.783775             1
2     2020-08-17 05:25:08:214  58.718430             1
3     2020-08-17 05:25:08:234  59.251448             1
4     2020-08-17 05:25:08:254  59.350180             1
...                       ...        ...           ...
4963  2020-08-17 05:28:53:429  25.010020             3
4964  2020-08-17 05:28:53:449  24.442004             3
4965  2020-08-17 05:28:53:469  24.680235             3
4966  2020-08-17 05:28:53:489  24.287477             3
4967  2020-08-17 05:28:53:509  24.285352             3

[4968 rows x 3 columns]

In [4]:
df['id'] = range(0, len(df))

In [5]:
df

                    TimeStamp  Magnitude  CoordinateID    id
0     2020-08-17 05:25:08:174  58.613036             1     0
1     2020-08-17 05:25:08:194  58.783775             1     1
2     2020-08-17 05:25:08:214  58.718430             1     2
3     2020-08-17 05:25:08:234  59.251448             1     3
4     2020-08-17 05:25:08:254  59.350180             1     4
...                       ...        ...           ...   ...
4963  2020-08-17 05:28:53:429  25.010020             3  4963
4964  2020-08-17 05:28:53:449  24.442004             3  4964
4965  2020-08-17 05:28:53:469  24.680235             3  4965
4966  2020-08-17 05:28:53:489  24.287477             3  4966
4967  2020-08-17 05:28:53:509  24.285352             3  4967

[4968 rows x 4 columns]

In [6]:
#Convert the timestamp to its correct data type
df['TimeStamp'] =  pd.to_datetime(df['TimeStamp'], format='%Y-%m-%d %H:%M:%S:%f')

## column ID as id

In [7]:
extracted_features = extract_features(df, column_id="id", column_sort="TimeStamp")

Feature Extraction: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10/10 [03:45<00:00, 22.55s/it]

In [8]:
extracted_features

variable,CoordinateID__abs_energy,CoordinateID__absolute_sum_of_changes,"CoordinateID__agg_autocorrelation__f_agg_""mean""__maxlag_40","CoordinateID__agg_autocorrelation__f_agg_""median""__maxlag_40","CoordinateID__agg_autocorrelation__f_agg_""var""__maxlag_40","CoordinateID__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","CoordinateID__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","CoordinateID__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","CoordinateID__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""","CoordinateID__agg_linear_trend__attr_""intercept""__chunk_len_50__f_agg_""max""",...,Magnitude__symmetry_looking__r_0.9500000000000001,Magnitude__time_reversal_asymmetry_statistic__lag_1,Magnitude__time_reversal_asymmetry_statistic__lag_2,Magnitude__time_reversal_asymmetry_statistic__lag_3,Magnitude__value_count__value_-1,Magnitude__value_count__value_0,Magnitude__value_count__value_1,Magnitude__variance,Magnitude__variance_larger_than_standard_deviation,Magnitude__variation_coefficient
id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4963,9.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4964,9.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4965,9.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4966,9.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4967,9.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
y = df.CoordinateID
y

_temporary_index_column
0       1
1       1
2       1
3       1
4       1
       ..
4963    3
4964    3
4965    3
4966    3
4967    3
Name: CoordinateID, Length: 4968, dtype: int64

In [10]:
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

impute(extracted_features)
features_filtered = select_features(extracted_features, y)

C:\Users\Anuj\Anaconda3\lib\site-packages\tsfresh\utilities\dataframe_functions.py:173: RuntimeWarning: The columns ['CoordinateID__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"'
 'CoordinateID__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"'
 'CoordinateID__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"'
 ... 'Magnitude__spkt_welch_density__coeff_2'
 'Magnitude__spkt_welch_density__coeff_5'
 'Magnitude__spkt_welch_density__coeff_8'] did not have any finite values. Filling with zeros.
  df.iloc[:, np.where(is_col_non_finite)[0]].columns.values), RuntimeWarning)

In [11]:
features_filtered.to_csv("ts.csv")

In [12]:
features_filtered.head(10)

variable,CoordinateID__abs_energy,CoordinateID__sum_values,CoordinateID__quantile__q_0.9,CoordinateID__quantile__q_0.8,CoordinateID__quantile__q_0.7,CoordinateID__quantile__q_0.6,CoordinateID__quantile__q_0.4,CoordinateID__quantile__q_0.3,CoordinateID__quantile__q_0.2,CoordinateID__quantile__q_0.1,...,Magnitude__mean,Magnitude__maximum,"Magnitude__fft_coefficient__attr_""real""__coeff_0","Magnitude__cwt_coefficients__coeff_0__w_5__widths_(2, 5, 10, 20)","Magnitude__cwt_coefficients__coeff_0__w_2__widths_(2, 5, 10, 20)","Magnitude__cwt_coefficients__coeff_0__w_20__widths_(2, 5, 10, 20)","Magnitude__cwt_coefficients__coeff_0__w_10__widths_(2, 5, 10, 20)",Magnitude__sum_values,Magnitude__median,Magnitude__abs_energy
id,,,,,,,,,,,,,,,,,,,,,
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,58.613036,58.613036,58.613036,22.734799,35.946873,11.367399,16.075931,58.613036,58.613036,3435.488037
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,58.783775,58.783775,58.783775,22.801025,36.051586,11.400513,16.122759,58.783775,58.783775,3455.532227
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,58.718430,58.718430,58.718430,22.775679,36.011510,11.387839,16.104837,58.718430,58.718430,3447.854004
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.251448,59.251448,59.251448,22.982426,36.338406,11.491213,16.251029,59.251448,59.251448,3510.734130
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.350180,59.350180,59.350180,23.020722,36.398957,11.510361,16.278109,59.350180,59.350180,3522.443848
5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.754646,59.754646,59.754646,23.177606,36.647013,11.588803,16.389042,59.754646,59.754646,3570.617676
6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.948448,59.948448,59.948448,23.252778,36.765870,11.626389,16.442197,59.948448,59.948448,3593.816407
7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.980734,59.980734,59.980734,23.265301,36.785671,11.632650,16.451052,59.980734,59.980734,3597.688476
8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.701001,59.701001,59.701001,23.156798,36.614113,11.578399,16.374329,59.701001,59.701001,3564.209473
9,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,59.279372,59.279372,59.279372,22.993257,36.355531,11.496628,16.258688,59.279372,59.279372,3514.043946

In [13]:
labels, counts = np.unique(features_filtered['CoordinateID__abs_energy'], return_counts=True)
print(labels, counts)

[1. 4. 9.] [1914 1669 1385]

In [14]:
labels, counts = np.unique(features_filtered['CoordinateID__sum_values'], return_counts=True)
print(labels, counts)

[1. 2. 3.] [1914 1669 1385]

In [15]:
labels, counts = np.unique(features_filtered['CoordinateID__quantile__q_0.8'], return_counts=True)
print(labels, counts)

[1. 2. 3.] [1914 1669 1385]

In [16]:
labels, counts = np.unique(features_filtered['Magnitude__mean'], return_counts=True)
print(labels, counts)

[20.99096921 21.07893649 21.08980649 ... 62.22976736 62.26067852
 62.42174398] [1 1 1 ... 3 3 3]

## column_id as CoordinateID

In [17]:
extracted_features = extract_features(df, column_id="CoordinateID", column_sort="TimeStamp")

Feature Extraction: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6/6 [00:17<00:00,  2.93s/it]

In [18]:
extracted_features

variable,Magnitude__abs_energy,Magnitude__absolute_sum_of_changes,"Magnitude__agg_autocorrelation__f_agg_""mean""__maxlag_40","Magnitude__agg_autocorrelation__f_agg_""median""__maxlag_40","Magnitude__agg_autocorrelation__f_agg_""var""__maxlag_40","Magnitude__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","Magnitude__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","Magnitude__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","Magnitude__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""","Magnitude__agg_linear_trend__attr_""intercept""__chunk_len_50__f_agg_""max""",...,id__symmetry_looking__r_0.9500000000000001,id__time_reversal_asymmetry_statistic__lag_1,id__time_reversal_asymmetry_statistic__lag_2,id__time_reversal_asymmetry_statistic__lag_3,id__value_count__value_-1,id__value_count__value_0,id__value_count__value_1,id__variance,id__variance_larger_than_standard_deviation,id__variation_coefficient
id,,,,,,,,,,,,,,,,,,,,,
1,2.816143e+06,549.761759,0.965987,0.965580,0.000340,56.685462,55.987083,55.128159,3.071421,56.461839,...,1.0,4.878150e+06,9.751204e+06,14619170.0,0.0,1.0,1.0,305282.916667,1.0,0.577652
2,2.691667e+06,482.356868,0.968362,0.968064,0.000289,58.784441,58.113081,57.261108,3.116866,58.352185,...,1.0,3.113231e+07,6.226018e+07,93383616.0,0.0,0.0,0.0,232130.000000,1.0,0.175327
3,2.462767e+06,401.352242,0.967630,0.967335,0.000305,63.686411,63.023383,62.176822,3.022474,63.297757,...,1.0,7.374006e+07,1.474764e+08,221209140.0,0.0,0.0,0.0,159852.000000,1.0,0.093524

In [19]:
# X and y must be of same size 
y = np.unique(df['CoordinateID'])

y

from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

impute(extracted_features)
features_filtered = select_features(extracted_features, y)

features_filtered.to_csv("ts2.csv")

features_filtered.head(10)

Empty DataFrame
Columns: []
Index: [1, 2, 3]